spring.application.name=temple-donation-system

spring.datasource.url=jdbc:mysql://b7vlre7yv8aijpbwt7pp-mysql.services.clever-cloud.com:3306/uqq0b8wll7w7o2j6

spring.datasource.username=uqq0b8wll7w7o2j6

spring.datasource.password=b7vlre7yv8aijpbwt7pp

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080